const MEDIA_BASE = (import.meta.env.VITE_MEDIA_URL || "http://127.0.0.1:8000").replace(/\/$/, "");
const media = (path) => `${MEDIA_BASE}/media/${path}`;

export const demoCategories = [
  {
    id: 1,
    name: "Smartphones",
    slug: "smartphones",
    image: media("categories/smartphones.jpg"),
    is_active: true,
  },
  {
    id: 2,
    name: "Laptops & Tablets",
    slug: "laptops-tablets",
    image: media("categories/laptops-tablets.jpg"),
    is_active: true,
  },
  {
    id: 3,
    name: "Headphones & Audio",
    slug: "headphones-audio",
    image: media("categories/headphones-audio.jpg"),
    is_active: true,
  },
  {
    id: 4,
    name: "Gaming Gear",
    slug: "gaming-gear",
    image: media("categories/gaming-gear.jpg"),
    is_active: true,
  },
  {
    id: 5,
    name: "Smart Watches & Wearables",
    slug: "wearables",
    image: media("categories/wearables.jpg"),
    is_active: true,
  },
  {
    id: 6,
    name: "Tech Accessories",
    slug: "tech-accessories",
    image: media("categories/tech-accessories.jpg"),
    is_active: true,
  },
];

export const demoProducts = [
  {
    id: 1,
    name: "Nova Edge Smartphone",
    slug: "nova-edge-smartphone",
    category: demoCategories[0],
    description: "A premium glass smartphone with a vivid edge display, fast daily performance, and a clean pro camera layout.",
    price: "999.00",
    old_price: "1199.00",
    image: media("products/nova-edge-smartphone.jpg"),
    stock: 18,
    rating: "4.82",
    is_featured: true,
  },
  {
    id: 2,
    name: "Orion Pro Laptop",
    slug: "orion-pro-laptop",
    category: demoCategories[1],
    description: "A slim premium laptop for work and creative flow, with a clean display and responsive keyboard.",
    price: "1499.00",
    old_price: "1799.00",
    image: media("products/orion-pro-laptop.jpg"),
    stock: 13,
    rating: "4.76",
    is_featured: true,
  },
  {
    id: 3,
    name: "Nocturne Halo Headphones",
    slug: "nocturne-halo-headphones",
    category: demoCategories[2],
    description: "Premium wireless over-ear headphones with soft cushions, deep listening comfort, and clean studio sound.",
    price: "649.00",
    old_price: "799.00",
    image: media("products/nocturne-halo-headphones.jpg"),
    stock: 22,
    rating: "4.80",
    is_featured: true,
  },
  {
    id: 4,
    name: "Apex Mechanical Keyboard",
    slug: "apex-mechanical-keyboard",
    category: demoCategories[3],
    description: "A premium mechanical keyboard with crisp switches, RGB lighting, and a responsive gaming feel.",
    price: "249.00",
    old_price: "319.00",
    image: media("products/apex-mechanical-keyboard.jpg"),
    stock: 30,
    rating: "4.72",
    is_featured: true,
  },
  {
    id: 5,
    name: "Aurum Active Smartwatch",
    slug: "aurum-active-smartwatch",
    category: demoCategories[4],
    description: "A clean round smartwatch with soft straps, daily wellness tracking, and a refined minimal profile.",
    price: "449.00",
    old_price: "549.00",
    image: media("products/aurum-active-smartwatch.jpg"),
    stock: 19,
    rating: "4.71",
    is_featured: true,
  },
  {
    id: 6,
    name: "Vanta USB-C Hub",
    slug: "vanta-usb-c-hub",
    category: demoCategories[5],
    description: "A multi-port USB hub with compact desk sizing and practical daily connectivity.",
    price: "119.00",
    old_price: "159.00",
    image: media("products/vanta-usb-c-hub.jpg"),
    stock: 55,
    rating: "4.55",
    is_featured: false,
  },
];
