# Generated by Django 5.2.14 on 2026-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
