# Generated by Django 5.2.14 on 2026-06-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='address',
            field=models.CharField(default='Marrakech, Maroc', max_length=255),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='MAD', max_length=8),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(default='fahdmama1@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='phone',
            field=models.CharField(default='+212 600280950', max_length=40),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_name',
            field=models.CharField(default='ECOM 3D', max_length=160),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp',
            field=models.CharField(default='+212 600 280950', max_length=40),
        ),
    ]
