# Generated by Django 5.2.14 on 2026-06-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price_text', models.CharField(blank=True, max_length=100)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('listing_url', models.URLField(max_length=1000, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='Avito', max_length=40)),
            ],
            options={
                'ordering': ('-scraped_at', '-id'),
            },
        ),
    ]
