# Generated by Django 5.2.14 on 2026-06-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitolisting',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
